---
- name: Install VS Code Extensions
  hosts: local
  vars:
    vscode_extensions:
      - alefragnani.Bookmarks
      - eamodio.gitlens
      - edwinhuish.better-comments-next
      - esbenp.prettier-vscode
      - formulahendry.auto-close-tag
      - Gruntfuggly.todo-tree
      - kevinrose.vsc-python-indent
      - ms-azuretools.vscode-docker
      - ms-python.flake8
      - ms-python.python
      - ms-python.vscode-pylance
      - njpwerner.autodocstring
      - redhat.ansible
      - redhat.vscode-yaml
      - rokoroku.vscode-theme-darcula
      - sanchitverma.block-comments
      - skellock.just
      - streetsidesoftware.code-spell-checker
      - tal7aouy.icons
      - tamasfe.even-better-toml
      - usernamehw.errorlens

  tasks:
    - name: Check if VS Code is installed
      ansible.builtin.shell: command -v code
      register: vscode_check
      ignore_errors: true
      changed_when: false

    - name: Install VS Code extensions
      ansible.builtin.shell: code --install-extension {{ item }} --force
      loop: "{{ vscode_extensions }}"
      when: vscode_check.rc == 0

    - name: Display message if VS Code not found
      ansible.builtin.debug:
        msg: "VS Code not found. Please install VS Code first."
      when: vscode_check.rc != 0
